# .github/workflows/cantina.yml
name: Cantina build and Deploy to Netlify
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - run: sudo apt-get update -y
      - run: sudo apt-get install asciidoctor linkchecker -y
      - uses: actions/checkout@v2
      - run: make
      - run: linkchecker ./dist/*.html
